image: Visual Studio 2017

matrix:
  fast_finish: true

platform:
- x64

configuration:
- Release

# http://www.appveyor.com/docs/installed-software
environment:
  QTDIR: "C:\\Qt\\5.13.0\\msvc2017_64"
  PATH: "%QTDIR%\\bin;%PATH%"
build:
  parallel: true

init:
- echo "Data loader init" %CD%
- echo %PATH%

install:
- echo "Data loader install"
- git submodule -q update --init --recursive

build_script:
- echo "Data loader build" %CD%
- echo %PATH%
- mkdir build
- cd build
- cmake --version
- cmake -G "Visual Studio 15 2017 Win64" ..
- cmake --build .
